"""empty message

Revision ID: 17c9410555f8
Revises: 47dd40caa20e
Create Date: 2016-03-09 13:43:14.959535

"""

# revision identifiers, used by Alembic.
revision = '17c9410555f8'
down_revision = '47dd40caa20e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'Family')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('Family', sa.VARCHAR(length=64), nullable=True))
    ### end Alembic commands ###
