"""Initial

Revision ID: 47dd40caa20e
Revises: None
Create Date: 2016-03-09 13:41:11.979309

"""

# revision identifiers, used by Alembic.
revision = '47dd40caa20e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('Family', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'Family')
    ### end Alembic commands ###
